### PR TITLE
MWTree and MWNode documentation

### PR DESCRIPTION
**Pull request by ilfreddy**
`MWTree` and `MWNode` classes are now sufficiently documented. 

Workflow to approve this pull request (and all other PRs about documentation)

1. pull the current branch
2. push it to the rtd-build in master
3. check that the commit does not alter anything else other than the documentation
4. check that the documentation produced is sane, meaningful and well written (language, grammar, typos)
5. check that all tests pass as requested
6. approve :-)

NOTE: This PR includes quite a few more changes other than just in the `MWNode` and `MWTree` classes because we had to refresh a few config files.

### CODE REVIEW

**Comment by robertodr** [comment]
If anyone with access can make me admin for the documentation project on readthedocs.org, I can activate the documentation build on pull request. It will be easier to review changes such as these

**Comment by ilfreddy** [comment]
I don't seem to be admin for mrcpp on readthedocs. Maybe @stigrj?

**Comment by Gabrielgerez** [comment]
> If anyone with access can make me admin for the documentation project on readthedocs.org, I can activate the documentation build on pull request. It will be easier to review changes such as these

I thought i enabled that already, but it is weird that it did not trigger on this PR. Is it not enough to just enable it in the `advanced settings > Build pull requests for this project` ?

**Comment by robertodr** [comment]
According to the docs, yes, that's enough. Investigating...

**Comment by robertodr** [comment]
The build starts, but then fails...

**Comment by robertodr** [comment]
Seems it needed a re-sync of the github hook. Now it shows the documentation build in the list of PR checks.

**Comment by robertodr** [comment]
Seems you need to debug the build on readthedocs before we can merge this.

**Comment by ilfreddy** [comment]
I don't quite get it. The last time I commited the build on readthedocs (which i triggered manually by pushing to the rtd-build branch) was working just fine. So something must ahve happened in the meantime...

**Comment by Gabrielgerez** [comment]
> Seems it needed a re-sync of the github hook. Now it shows the documentation build in the list of PR checks. It's also building the docs.

How did you do this?



> I don't quite get it. The last time I commited the build on readthedocs (which i triggered manually by pushing to the rtd-build branch) was working just fine. So something must have happened in the meantime...

did you do a rebase before creating the PR? I think it might be some other issues that are crashing

**Comment by ilfreddy** [comment]
Not clear to me what happened but the doc build seems fine now after I force-pushed my own version

**Comment by ilfreddy** [comment]
This PR is btw from the rtd-build which is on upstream (not my own fork, my bad!).

**Comment by robertodr** [comment]
> How did you do this?

By reading the docs 😄 https://docs.readthedocs.io/en/stable/guides/pull-requests.html#troubleshooting

**Review by robertodr — APPROVED** [review]
LGTM but I leave here some food for thought. In general, I prefer the Doxygen documentation to be only in the header files, because they are readable once the library is installed and I can have a look at the documentation from the source directly (and I think IDEs can read it as well)

It's up to you to decide whether it goes in the header or the source file. But at least do it consistently, not a little bit here and little bit there.

**Pull request merged**
