### PR TITLE
Make bot skippable

### PR DESCRIPTION
**Pull request by robertodr**
It is now possible to skip the bot entirely by adding any of the following to the commit message: `[skip bot]`, `[bot skip]`, `[skip danger]` or `[danger skip]`. Note that the bot is run last in the Travis build matrix.

### CODE REVIEW

**Comment by robertodr** [comment]
This could be extended to also run `clang-tidy` @bjorgve

**Comment by bjorgve** [comment]
Do you mean make the bot warn when clang-tidy prints warnings?

**Comment by robertodr** [comment]
I meant adding a stage to the build that runs `clang-tidy`, independently of the bot, and prints a report.

**Comment by robertodr** [comment]
No, this is ready to go.

**Pull request merged**
