### PR TITLE
[WIP] STL_containers in constructors

### PR DESCRIPTION
**Pull request by bjorgve**
Making several constructors accept std::vector<type> as input. This makes implementing vampyr functionality much easier. As a bonus it's a step towards a modern code.

### CODE REVIEW

**Comment by stigrj** [comment]
You'll need to rebase on `upstream/master`

**Comment by robertodr** [comment]
Nice. Will be especially useful to translate `double * r` to `std:array<double, D> r`. Is there some underlying design issue to having the data member themselves be STL containers? Here you pass `std::vector` but then "unpack" the raw pointer using `.data()`.

**Comment by stigrj** [comment]
The data is passed down to the `NodeIndex` class which was originally intended to be as simple and lightweight as possible, since it will be used millions and billions of times in a full calculation. Also we explicitly avoided any non-fundamental data types at this low level to simplify MPI routines.

**Comment by bjorgve** [comment]
What's the advantage of using `std::array<double, D>` over 'std::vector<double>` ? In vampyr both lists and np.arrrays are accepted as input when `std::vector` is used, but with `std::array` only regular lists are accepted.

**Comment by bjorgve** [comment]
I'll go for `std::array`. I don't think @Gabrielgerez will mind changing his `np.array` to regular lists.

**Pull request merged**
