### PR TITLE
Update Autocmake

### PR DESCRIPTION
**Pull request by robertodr**
Resolve a couple of issues when using MRCPP as an external dependency:

1. `CMAKE_MODULE_PATH` might have been populated by the superproject and include CMake modules that conflict with those in MRCPP. This was solved in https://github.com/dev-cafe/autocmake/pull/256
2. Use `PROJECT_{BINARY,SOURCE}_DIR` rather than `CMAKE_{BINARY,SOURCE}_DIR`. The former is within the scope of MRCPP as a subproject, whereas the latter will refer to the superproject.

### CODE REVIEW

**Comment by robertodr** [comment]
Similar update of Autocmake might be needed in MRChem. I am looking at VAMPyR myself now, as I wanted to create a Docker image to run it interactively on MyBinder

**Comment by bjorgve** [comment]
It doesn't seem to work for me.

**Comment by stigrj** [comment]
The compiler flag CMake files are not found: `cmake/compiler_flags/GNU.CXX.cmake` etc.

**Comment by robertodr** [comment]
Yeah. I fixed it, but forgot to push.

**Pull request merged**
