### PR TITLE
Fix arch-flags

### PR DESCRIPTION
**Pull request by stigrj**

### CODE REVIEW

**Review by robertodr — CHANGES_REQUESTED** [review]
You can ditch the call to the function entirely and just set _arch_flag to the value known to be recognised by the compiler

**Comment by stigrj** [comment]
you mean like this?
```
  if(CMAKE_CXX_COMPILER_ID MATCHES GNU)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native")
    message(STATUS "Adding architecture-specific compiler flag: -march=native")
  endif()
  if(CMAKE_CXX_COMPILER_ID MATCHES Clang)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native")
    message(STATUS "Adding architecture-specific compiler flag: -march=native")
  endif()
  if(CMAKE_CXX_COMPILER_ID MATCHES Intel)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -xHost")
    message(STATUS "Adding architecture-specific compiler flag: -xHost")
  endif()
```

**Comment by robertodr** [comment]
> you mean like this?
> 
> ```
>   if(CMAKE_CXX_COMPILER_ID MATCHES GNU)
>     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native")
>     message(STATUS "Adding architecture-specific compiler flag: -march=native")
>   endif()
>   if(CMAKE_CXX_COMPILER_ID MATCHES Clang)
>     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native")
>     message(STATUS "Adding architecture-specific compiler flag: -march=native")
>   endif()
>   if(CMAKE_CXX_COMPILER_ID MATCHES Intel)
>     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -xHost")
>     message(STATUS "Adding architecture-specific compiler flag: -xHost")
>   endif()
> ```

Yes. Or:
```cmake
if(CMAKE_CXX_COMPILER_ID MATCHES GNU)
  set(_arch_flag "-march=native")
endif()
if(CMAKE_CXX_COMPILER_ID MATCHES Clang)
  set(_arch_flag "-march=native")
endif()
if(CMAKE_CXX_COMPILER_ID MATCHES Intel)
  set(_arch_flag "-xHost")
endif()
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${_arch_flag}")
message(STATUS "Adding architecture-specific compiler flag: ${_arch_flag}")
```

**Comment by robertodr** [comment]
And you can remove the `set_compiler_flag.cmake` file. Much good that it did...

**Review by robertodr — APPROVED** [review]
Golden

**Pull request merged**
