### PR TITLE
Release prep

### PR DESCRIPTION
**Pull request by stigrj**
`MRCPP-1.3.0` coming up

### CODE REVIEW

**Review by robertodr — APPROVED** [review]

**Comment by stigrj** [comment]
What the :cursing_face: happened to Eigen on Travis?

**Comment by robertodr** [comment]
Maybe you can switch to using bionic rather than xenial.

**Comment by robertodr** [comment]
Sorry, I stepped on your toes with my changes in `.travis.yml`... Is Eigen 3.3.4 enough for MRCPP and MRChem?

**Comment by stigrj** [comment]
Haha, yes I think so. 3.3.90 does not work, though

**Comment by robertodr** [comment]
> Haha, yes I think so. 3.3.90 does not work, though

I think that's their `master` branch.

**Pull request merged**
