### PR TITLE
Negative scale on single root node

### PR DESCRIPTION
**Pull request by stigrj**
- [x] Switch to single root PBC
- [x] Make tests pass
- [x] Set restrictions on world parameters when running PBC
- [x] Cleanup

### CODE REVIEW

**Comment by stigrj** [comment]
I can't remember, @bjorgve , were we supposed to keep the `[-1,1]` possibility for the zero-scale reaching operator? Or should PBC _always_ be done on `[0,1]`?

**Comment by bjorgve** [comment]
Both `[-1, 1]` and `[0, 1]` is better, but `[0, 1]` is fine.

**Review by bjorgve — APPROVED** [review]
It looks good to me, I think there should be a sanity check in the Poisson and Helmholtz operator constructors. The reach/root constructors should only work for periodic `mra`. 

I suggest we wait with the merge until I'm finished with periodic mrchem.

**Comment by bjorgve** [comment]
@stigrj can you think about a solution for `VAMPyR`s build prec in the operator constructions?

**Comment by bjorgve** [comment]
The `apply_near_field` does not appear to work as expected for negative scale operators.

**Comment by stigrj** [comment]
Dead end

**Pull request closed without merging**
