### PR TITLE
Fix Eigen3 cmake as in MRChem

### PR DESCRIPTION
**Pull request by ilfreddy**

### CODE REVIEW

**Comment by robertodr** [comment]
@stigrj maybe a new release?

**Comment by stigrj** [comment]
on it

**Comment by stigrj** [comment]
why this weird `before-git-migration` instead of a proper version number?

**Comment by robertodr** [comment]
The `Eigen3Config.cmake` file is broken with all released versions of Eigen when doing the superbuild with `FetchContent`: https://gitlab.com/libeigen/eigen/-/blob/master/cmake/Eigen3Config.cmake.in

**Pull request merged**
