### PR TITLE
Handle filters

### PR DESCRIPTION
**Pull request by robertodr**
This reworks handling of filters according to what we discussed yesterday at the meeting.

- The `get_mw_filter_dir` function takes the place of the `MW_FILTER_DIR` preprocessor macro. It is also responsible for checking the `MRCPP_FILTER_DIR` env-var.
The function gets the location of the library and "walks" upwards from there to the directory holding the filters.
- Filters are always copied/installed to  `share/MRCPP/mwfilters`, either under `<build-dir>` or `<install-dir>`.

### CODE REVIEW

**Comment by stigrj** [comment]
So now the `INSTALL_FILTER` option is gone and the filters are always copied both to <build-dir> and <install-dir>?

**Comment by robertodr** [comment]
Correct, but this is still WIP: I am now testing working with a preinstalled MRCPP.

**Comment by robertodr** [comment]
Not quite correct implementation, it would seem.

**Comment by robertodr** [comment]
I think I'll just translate the filters to source files, rather than do contortions with filesystem operations...

**Comment by robertodr** [comment]
It takes ages to compile this on my laptop. I don't think having these as code is a good solution either... :thinking:

**Comment by robertodr** [comment]
@bjorgve  and I are cooking something else. Closing.

**Pull request closed without merging**
